### ISSUE TITLE
error while creating topology using shell script

### ISSUE THREAD

**Issue by jenniexie** [openweave/happy#21]
This is to track one issue when using shell script to creating topology, some error happened.

jexie@jexie0:~/github_jennie/openweave-core/src/test-apps/happy/topologies/standalone$ ./three_nodes_on_tap_thread_weave.sh 
Traceback (most recent call last):
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/bin/weave-node-configure", line 75, in <module>
    cmd.run()
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 376, in run
    self.__init_node(self.node_name, self.node_params)
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 336, in __init_node
    weave_params = self.__get_weave_params(node, node_params)
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 206, in __get_weave_params
    params['iid'] = self.weave_state.EUI64toIID(params['eui64'])
AttributeError: Weave instance has no attribute 'EUI64toIID'
Traceback (most recent call last):
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/bin/weave-node-configure", line 75, in <module>
    cmd.run()
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 376, in run
    self.__init_node(self.node_name, self.node_params)
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 336, in __init_node
    weave_params = self.__get_weave_params(node, node_params)
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 206, in __get_weave_params
    params['iid'] = self.weave_state.EUI64toIID(params['eui64'])
AttributeError: Weave instance has no attribute 'EUI64toIID'
Traceback (most recent call last):
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/bin/weave-node-configure", line 75, in <module>
    cmd.run()
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 376, in run
    self.__init_node(self.node_name, self.node_params)
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 336, in __init_node
    weave_params = self.__get_weave_params(node, node_params)
  File "/usr/local/google/home/jexie/openweave-core/src/test-apps/happy/lib/WeaveNodeConfigure.py", line 206, in __get_weave_params
    params['iid'] = self.weave_state.EUI64toIID(params['eui64'])
AttributeError: Weave instance has no attribute 'EUI64toIID'

**Comment by jenniexie** [comment]
This is my local setup issue, because my openweave path is not point correctly in "~/.bashrc" file:
`export PATH=$PATH:~/github/openweave-core/src/test-apps/happy/bin`
